CREATE DATABASE skillhub

USE skillhub

CREATE TABLE USERS(
    UserID CHAR(50) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    UserName VARCHAR(255),
    PASSWORD VARCHAR(255)
)